[package]
name = "drainarr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
bytesize = "2.3.1"
chrono = { version = "0.4.44", features = ["serde"] }
reqwest = { version = "0.13.4", features = ["json", "query", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
url = { version = "2.5.8", features = ["serde"] }
